const assert = require("node:assert");
const isCombinatorDevice = require("./isCombinatorDevice");

assert(
  isCombinatorDevice([
    { name: "Singen", value: 0.23 },
    { name: "Tanzen", value: 0.88 },
    { name: "Lachen", value: 0.1 },
    { name: "Unused Control 4", value: 0 },
    { name: "Unused Control 5", value: 0 },
    { name: "Unused Control 6", value: 0 },
    { name: "Unused Control 7", value: 0 },
    { name: "Unused Control 8", value: 0 },
    { name: "Unused Control 9", value: 0 },
    { name: "Unused Control 10", value: 0 },
    { name: "Unused Control 11", value: 0 },
    { name: "Unused Control 12", value: 0 },
    { name: "Unused Control 13", value: 0 },
    { name: "Unused Control 14", value: 0 },
    { name: "Unused Control 15", value: 0 },
    { name: "Unused Control 16", value: 0 },
    { name: "Unused Control 17", value: 0 },
    { name: "Unused Control 18", value: 0 },
    { name: "Unused Control 19", value: 0 },
    { name: "Unused Control 20", value: 0 },
    { name: "Unused Control 21", value: 0 },
    { name: "Unused Control 22", value: 0 },
    { name: "Unused Control 23", value: 0 },
    { name: "Unused Control 24", value: 0 },
    { name: "Unused Control 25", value: 0 },
    { name: "Unused Control 26", value: 0 },
    { name: "Unused Control 27", value: 0 },
    { name: "Unused Control 28", value: 0 },
    { name: "Unused Control 29", value: 0 },
    { name: "Unused Control 30", value: 0 },
    { name: "Unused Control 31", value: 0 },
    { name: "Unused Control 32", value: 0 },
    { name: "Hello", value: 0.11 },
    { name: "Goodbye", value: 0.12 },
    { name: "Unused Switch 3", value: 0 },
    { name: "Unused Switch 4", value: 0 },
    { name: "Unused Switch 5", value: 0 },
    { name: "Unused Switch 6", value: 0 },
    { name: "Unused Switch 7", value: 0 },
    { name: "Unused Switch 8", value: 0 },
    { name: "Unused Switch 9", value: 0 },
    { name: "Unused Switch 10", value: 0 },
    { name: "Unused Switch 11", value: 0 },
    { name: "Unused Switch 12", value: 0 },
    { name: "Unused Switch 13", value: 0 },
    { name: "Unused Switch 14", value: 0 },
    { name: "Unused Switch 15", value: 0 },
    { name: "Unused Switch 16", value: 0 },
    { name: "Unused Switch 17", value: 0 },
    { name: "Unused Switch 18", value: 0 },
    { name: "Unused Switch 19", value: 0 },
    { name: "Unused Switch 20", value: 0 },
    { name: "Unused Switch 21", value: 0 },
    { name: "Unused Switch 22", value: 0 },
    { name: "Unused Switch 23", value: 0 },
    { name: "Unused Switch 24", value: 0 },
    { name: "Unused Switch 25", value: 0 },
    { name: "Unused Switch 26", value: 0 },
    { name: "Unused Switch 27", value: 0 },
    { name: "Unused Switch 28", value: 0 },
    { name: "Unused Switch 29", value: 0 },
    { name: "Unused Switch 30", value: 0 },
    { name: "Unused Switch 31", value: 0 },
    { name: "Unused Switch 32", value: 0 },
    { name: "Enabled", value: 1 },
    { name: "Mixer Level", value: 0.5 },
  ]) === true,
  "When given parameters from a combinator device, it should return true"
);

assert(
  isCombinatorDevice([
    { name: "Singen", value: 0.23 },
    { name: "Tanzen", value: 0.88 },
    { name: "Lachen", value: 0.1 },
  ]) === false,
  "When given parameters that are not from a combinator device, it should return false"
);
