const assert = require("node:assert");

const padIndexToClipIndex = require("./padIndexToClipIndex");

const testCases = [
  { padIndex: 81, clipIndex: 0 },
  { padIndex: 82, clipIndex: 1 },
  { padIndex: 83, clipIndex: 2 },
  { padIndex: 84, clipIndex: 3 },
  { padIndex: 85, clipIndex: 4 },
  { padIndex: 86, clipIndex: 5 },
  { padIndex: 87, clipIndex: 6 },
  { padIndex: 88, clipIndex: 7 },
  { padIndex: 71, clipIndex: 8 },
  { padIndex: 72, clipIndex: 9 },
  { padIndex: 73, clipIndex: 10 },
  { padIndex: 74, clipIndex: 11 },
  { padIndex: 75, clipIndex: 12 },
  { padIndex: 76, clipIndex: 13 },
  { padIndex: 77, clipIndex: 14 },
  { padIndex: 78, clipIndex: 15 },
  { padIndex: 61, clipIndex: 16 },
  { padIndex: 62, clipIndex: 17 },
  { padIndex: 63, clipIndex: 18 },
  { padIndex: 64, clipIndex: 19 },
  { padIndex: 65, clipIndex: 20 },
  { padIndex: 66, clipIndex: 21 },
  { padIndex: 67, clipIndex: 22 },
  { padIndex: 68, clipIndex: 23 },
  { padIndex: 51, clipIndex: 24 },
  { padIndex: 52, clipIndex: 25 },
  { padIndex: 53, clipIndex: 26 },
  { padIndex: 54, clipIndex: 27 },
  { padIndex: 55, clipIndex: 28 },
  { padIndex: 56, clipIndex: 29 },
  { padIndex: 57, clipIndex: 30 },
  { padIndex: 58, clipIndex: 31 },
  { padIndex: 41, clipIndex: 32 },
  { padIndex: 42, clipIndex: 33 },
  { padIndex: 43, clipIndex: 34 },
  { padIndex: 44, clipIndex: 35 },
  { padIndex: 45, clipIndex: 36 },
  { padIndex: 46, clipIndex: 37 },
  { padIndex: 47, clipIndex: 38 },
  { padIndex: 48, clipIndex: 39 },
  { padIndex: 31, clipIndex: 40 },
  { padIndex: 32, clipIndex: 41 },
  { padIndex: 33, clipIndex: 42 },
  { padIndex: 34, clipIndex: 43 },
  { padIndex: 35, clipIndex: 44 },
  { padIndex: 36, clipIndex: 45 },
  { padIndex: 37, clipIndex: 46 },
  { padIndex: 38, clipIndex: 47 },
  { padIndex: 21, clipIndex: 48 },
  { padIndex: 22, clipIndex: 49 },
  { padIndex: 23, clipIndex: 50 },
  { padIndex: 24, clipIndex: 51 },
  { padIndex: 25, clipIndex: 52 },
  { padIndex: 26, clipIndex: 53 },
  { padIndex: 27, clipIndex: 54 },
  { padIndex: 28, clipIndex: 55 },
  { padIndex: 11, clipIndex: 56 },
  { padIndex: 12, clipIndex: 57 },
  { padIndex: 13, clipIndex: 58 },
  { padIndex: 14, clipIndex: 59 },
  { padIndex: 15, clipIndex: 60 },
  { padIndex: 16, clipIndex: 61 },
  { padIndex: 17, clipIndex: 62 },
  { padIndex: 18, clipIndex: 63 },
];

for (const testCase of testCases) {
  assert(
    padIndexToClipIndex(testCase.padIndex) === testCase.clipIndex,
    `The clip index for pad ${testCase.padIndex} should be ${testCase.clipIndex}`
  );
}
